# Generated by Django 5.0.3 on 2024-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
